baseurl      = "localhost"
title        = "alejandro bustos nuñez"
languageCode = "es-cl"
theme        = "hello-friend-ng"
paginate     = 10
defaultContentLanguage = "es"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Ingeniero en Informática"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Página personal de alejandro"
  keywords = "homepage, blog, filosofía"
  images = [""]


[[params.social]]
  name = "github"
  url = "https://github.com/newale"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/alejandrobustosn"

[taxonomies]
    category = "essays"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.es]
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.es.params]
    subtitle  = "A simple theme for Hugo"

    [languages.es.params.logo]
      logoText = "ale"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "essays"
    name       = "Ensayos"
    url        = "/essays"
  
  [[menu.main]]
    identifier = "experience"
    name       = "Experiencia"
    url        = "/experience"

  [[menu.footer]]
    identifier = "experience"
    name       = "Experiencia"
    url        = "/experience"