baseURL: "https://alejandro.earth"
title: Alejandro Bustos Nuñez
pagination:
  pagerSize: 5
theme: PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: G-8KQ0WJX6F0
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Sitio personal
  description: "Alejandro Bustos Nuñez Sitio Web Personal"
  keywords: [Blog, Portfolio, PaperMod]
  author: [""]
  DateFormat: "January, 2006"
  defaultTheme: light
  disableThemeToggle: true
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  params:
  mainSections:
    - posts
  label:
    text: "alejandro"
    icon: /apple-touch-icon.png
    iconHeight: 35
  profileMode:
    enabled: false
    title: Alejandro Bustos Nuñez
    subtitle: "Ingeniero en Informática, diplomado en Filosofía y Ciencias (2023), e Inteligencia Artificial (2024)"
    buttons:
      - name: Blog
        url: posts
      - name: Curriculum
        url: cv
  homeInfoParams: 
    Title: "¡Hola \U0001F44B!"
    Content: "Sitio web personal, donde puedes encontrar mi CV y algunos articulos. Para ponerte en contacto, puedes hacerlo a través de linkedin"
    socialIcons:
      - name: linkedin
        url: "https://www.linkedin.com/in/alejandrobustosn"
      - name: github
        url: "https://github.com/newale"
  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: blog
      name: blog
      url: /posts/
      weight: 10
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
